<?php
/**
 * @file
 * Simple mail using Drupal API. Messaging method plug-in
 * 
 * @ TO DO Review filtering
 */

/**
 * Implementation of hook_messaging
 */
function messaging_privatemsg_messaging($op) {
  switch($op) {
    case 'send methods':
      $info['privatemsg'] = array(
        'title' => 'Privatemsg',
        'name' => t('Private message'),
        'group' => 'web',
        'type' => MESSAGING_TYPE_SEND,
        'address_type' => 'user', // Which kind of address this method uses
        'access' => 'read privatemsg',
        'glue' => "\n",
        'description' => t('Send messages through Privatemsg'),
        'send callback' => 'messaging_privatemsg_send_msg', // Sending callback
        'filter' => 'messaging_filter', // Default filter for this format
      );
      return $info;  
  }
}

/**
 * Send mail message to user accounts
 * 
 * Privatemsg API documentation on http://drupal.org/node/369399
 * 
 * @param $destination
 *   User account or user id
 */
function messaging_privatemsg_send_msg($destination, $message) {
  // Prepare the privatemsg parameters
  $recipients = array(messaging_user_object($destination));
  // this could be broken by minor changes to privatemsg_new_thread, which has an API different from its implementation at present
  $ret = privatemsg_new_thread($recipients, $message->get_subject(), $message->get_body(), array('author' => $message->get_sender()));
  return $ret['success'];
}

/**
 * Implementation of hook_disable()
 */
function messaging_privatemsg_disable() {
  messaging_method_disable('privatemsg');
}