<?php
/**
 * @file
 * Simple mail using Drupal API. Messaging method plug-in
 */

/**
 * Implementation of hook_messaging
 */
function messaging_mail_messaging($op = 'info') {
  switch($op) {
    case 'send methods':
      $info['mail'] = array(
        'name' => t('Mail'),
        'send' => 'messaging_mail_send',
        'type' => MESSAGING_TYPE_PUSH,   
      );
      return $info;  
  }
}

/**
 * Send mail message to user account
 */
function messaging_mail_send($account, $message) {
  $mailkey = 'message-'.$message['type'];
  $to = $account->mail;
  $subject = messaging_message_render($message['subject'], '');
  if (isset($message['body']['footer'])) {
    $message['body']['footer'] = array('#prefix' => "\n--", '#text' => $message['body']['footer']);
  }
  $body = messaging_message_render($message['body'], "\n");
  return drupal_mail($mailkey, $to, $subject, $body);
}
 