<?php
// $Id$
/**
 * @file
 * Simple mail using Drupal API. Messaging method plug-in
 * 
 * This is also the reference implementation of sending method plug-ins
 */

/**
 * Implementation of hook_messaging()
 * 
 * Currently the only operation supported is 'send methods' that will retrieve and array
 * with information fo the sending methods provided by this module.
 * 
 * @param $op
 *   Type of information to retrieve.
 * @return mixed
 *   Depending on $op   
 */
function messaging_mail_messaging($op, $type = NULL) {
  switch($op) {
    case 'send methods':
      $info['mail'] = array(
        'title' => 'Drupal mail',
        'name' => t('Mail'), // Name for display
        'description' => t('Send e-mails using the default Drupal mail library.'),
        'address_type' => 'mail', // Which kind of address this method uses
        'group' => 'mail', // Class of sending method
        'type' => MESSAGING_TYPE_SEND,  // Method type: push || pull
        'glue' => "\n", // Glue for message body lines
        'footer' => "\n--",  // Separator for message footer
        'send callback' => 'messaging_mail_send_msg', // Sending callback
        'class' => 'Messaging_Method_Mail',
        'filter' => 'messaging_plaintext', // Default filter for this format
        'anonymous' => TRUE, // This method supports anonymous destinations
      );
      return $info;  
  }
}



/**
 * Send mail message to user account
 * 
 * This is a callback function that will be invoked from messaging delivery methods
 * 
 * @see messaging_message_send()
 * @see drupal_mail()
 * 
 * @param $destination
 *   Single email address
 * @param $message
 *   Message array
 * @param $params
 *   Optional parameters for this method type
 */
function messaging_mail_send_msg($address, $message, $params = array()) {
  // Build the message in drupal mail format
  $mail = $message->send_method()->mail_build($address, $message, $params);
  return drupal_mail_send($mail);
}

/**
 * Implementation of hook_disable()
 */
function messaging_mail_disable() {
  messaging_method_disable('mail');
}