<?php
/**
 * @file
 * Simple mail using Drupal API. Messaging method plug-in
 * 
 * @ TO DO Review filtering
 */

/**
 * Implementation of hook_messaging
 */
function messaging_private_messaging($op) {
  switch($op) {
    case 'send methods':
      $info['privatemsg'] = array(
        'name' => t('Privatemsg'),
        'send' => 'messaging_private_send',
        'type' => MESSAGING_TYPE_PUSH,
        'render' => 'messaging_private_render',
        'access' => 'access private messages',
      );
      return $info;  
  }
}

/**
 * Message render callback
 */
function messaging_private_render($message, $info) {
  // Preformat data
  $info['glue'] = '';
  $message['subject'] = messaging_message_render($message['subject'], $info);
  $info['glue'] = "\n";
  $message['body'] = messaging_message_render($message['body'], $info);  
}

/**
 * Send mail message to user account
 */
function messaging_private_send($account, $message) {
  // Hand over to privatemsg  
  privatemsg_send_privatemsg($account, $message['subject'], $message['body']);
  // @ TO DO How to check for success?
  return TRUE;
}
 